<?php
require_once('GermanNumerus.php');
use \ulrischa\GermanNumerus;

echo GermanNumerus::pluralize("Kopf");
echo "<br />";
echo  GermanNumerus::pluralize("Köpfe");
echo "<br />";
echo  GermanNumerus::pluralize("Haus");
echo "<br />";
echo  GermanNumerus::pluralize("Häuser");
echo "<br />";
echo  GermanNumerus::pluralize("Mann");
echo "<br />";
echo  GermanNumerus::pluralize("Männer");
echo "<br />";
echo  GermanNumerus::pluralize("Stinker");
echo "<br />";
echo  GermanNumerus::pluralize("Amt");
echo "<br />";
echo  GermanNumerus::pluralize("Ämter");
echo "<br />";
echo  GermanNumerus::pluralize("Kaktus");
echo "<br />";
echo  GermanNumerus::pluralize("Kakteen");
echo "<br />";
echo  GermanNumerus::pluralize("Visum");
echo "<br />";
echo  GermanNumerus::pluralize("Bus");
echo "<br />";
echo  GermanNumerus::pluralize("Album");
echo "<br />";
echo  GermanNumerus::pluralize("Atlas");
echo "<br />";
echo  GermanNumerus::pluralize("Firma");
echo "<br />";
echo  GermanNumerus::pluralize("Globus");
echo "<br />";
echo  GermanNumerus::pluralize("Komma");
echo "<br />";
echo  GermanNumerus::pluralize("Lob");
echo "<br />";
echo  GermanNumerus::pluralize("Marke");
echo "<br />";
echo  GermanNumerus::pluralize("Monitor");
echo "<br />";
echo  GermanNumerus::pluralize("Motor");
echo "<br />";
echo  GermanNumerus::pluralize("Studie");
echo "<br />";
echo  GermanNumerus::pluralize("Salz");
echo "<br />";
echo  GermanNumerus::pluralize("Salze");
echo "<br />";
echo  GermanNumerus::pluralize("Schule");
echo "<br />";
echo  GermanNumerus::pluralize("Schulen");
echo "<br />";
echo  GermanNumerus::pluralize("Bodenverunreinigung");
echo "<br />";
echo  GermanNumerus::pluralize("Wein");
echo "<br />";
echo  GermanNumerus::pluralize("Verein");
echo "<br />";
echo  GermanNumerus::pluralize("Fröhlichsein");
echo "<br />";
echo  GermanNumerus::pluralize("Heim");
echo "<br />";
echo  GermanNumerus::pluralize("Leim");
echo "<br />";
echo '<hr />';
echo  GermanNumerus::singularize("Bodenverunreinigungen");
echo "<br />";
echo  GermanNumerus::singularize("Salze");
echo "<br />";
echo  GermanNumerus::singularize("Köpfe");
echo "<br />";
echo  GermanNumerus::singularize("Busse");
echo "<br />";
echo  GermanNumerus::singularize("Atlanten");
echo "<br />";
echo  GermanNumerus::singularize("Häuser");
echo "<br />";
echo  GermanNumerus::singularize("Weine");
echo "<br />";